### ISSUE TITLE
Navbar element does not indicate it active when user is active on that section

### ISSUE THREAD

**Issue by mofirojean** [transkript/transkript-fe#52]
### Description

when user clicks an item in the menu, the element does not show  that it is active 

image of this issue can be seen below 
where a user is active in the home page section but the navbar element does not indicate that its active
![Screenshot from 2022-08-03 16-03-07](https://user-images.githubusercontent.com/93985482/182655015-293a6c65-76a0-4fbe-8061-9eeea9e9a558.png)

A possible solution can be seen below
It should indicate the user is actively in the home page
![Screenshot from 2022-08-03 17-05-12](https://user-images.githubusercontent.com/93985482/182656914-cd957b39-12ff-4396-986f-61a248369867.png)

**Comment by elroykanye** [comment]
Closing as it is resolved by #108
