### ISSUE TITLE
Subject not deleting

### ISSUE THREAD

**Issue by AkumbomWesley** [transkript/transkript-fe#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the clicking the delete button in order to delete a subject from the subject list, the subject is not deleted until the page is refreshed

### Expected Behavior

Subject is supposed to delete immediately after the delete button is clicked and not only after page is refreshed

### Steps To Reproduce

login
click on subject tab
click add button to add subject name, coefficient,subject code
click the delete button

### Environment

```markdown
- OS:kali 2022.2
- Node:16.15.0
- npm:8.5.5
```

**Comment by elroykanye** [comment]
Closing as it is resolved by #108
