### ISSUE TITLE
A duplicate success message pops up  when the add button is clicked

### ISSUE THREAD

**Issue by mofirojean** [transkript/transkript-fe#59]
### Description

when the the  save button is clicked a duplicate success message pops up

An image of the issue can be seen below
![Screenshot from 2022-08-04 11-19-44](https://user-images.githubusercontent.com/93985482/182824432-84f5bb46-2603-41b7-bcb1-03ceb3d90845.png)
 
similar problem
![Screenshot from 2022-08-04 11-24-01](https://user-images.githubusercontent.com/93985482/182825156-ff163550-e8fc-494c-ac55-4a12f127e64f.png)

**Comment by elroykanye** [comment]
Closing as it is resolved by #108
