### ISSUE TITLE
Implement a loading message or a spinner on login

### ISSUE THREAD

**Issue by mulfranck** [transkript/transkript-fe#65]
### Description

Implement a loading message or a spinner on the login btn to let the user know that the login is on process

**Comment by elroykanye** [comment]
This is going to be needed in multiple sections of the app. Maybe it is a fine idea to locate these first 🤔

**Comment by mulfranck** [comment]
> . Maybe it is a fine idea to locate these first thinking

A lovely idea as it would be helpful, when working on this issue. 👍🏽 
Should I just update this comment or the issue is itself with any of such areas I meet?
