### ISSUE TITLE
Automatically logged in, without checking the "Remember me" box

### ISSUE THREAD

**Issue by mulfranck** [transkript/transkript-fe#68]
### Description

Without checking the box for `Remember me` on the login page, if I login and my browser tab is close, the browser itself close without manually logging out.
If the browser is open some few seconds late and navigated to `https://ireportcard-client.vercel.app/student`, or a click on the history or recent tabs - I am automatically logged in. This should not be so if I never clicked on the `Remember me`.

Also, my password is present in the `old password` input field, requiring just to enter a new password and the password is changed. Filling the password for the `old password` input field is required, as any person can change this if I am remembered by the browser.

**Comment by elroykanye** [comment]
The remembered checkbox doesn't work for now. All sessions are persisted in the database for 1440 minutes. I think the title of this issue should be more appropriate, relating more to the issue itself and sounding less of a personal statement / feeling :)

**Comment by elroykanye** [comment]
Closing this because this has been resolved by #108
