### ISSUE TITLE
Unstyled page appears appears for a few seconds before welcome/index page appears

### ISSUE THREAD

**Issue by Serge-NSN** [transkript/transkript-fe#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the site is accessed, it displays the index page without css for a few seconds. Thought it was my browser at fault but that seems not to be the case (both on PC and on mobile). It's difficult to notice this bug because it happens just for about 1.5seconds. 

### Expected Behavior

The index page when visited,  should only display the styled content.

### Steps To Reproduce

1. Using Chrome 
2. Open https://ireportcard.vercel.app
3. Observe what happens before the beautiful page appears

### Environment

```markdown
- OS: Windows 10, Android v 12
```

### Anything else?

![VideoCapture_20230207-060725](https://user-images.githubusercontent.com/81696072/217156074-76b04afd-5852-4229-b734-aea170085351.jpg)

**Comment by Andy-Kin3** [comment]
I don't see what you are saying because it works fine for me the page loads
instantly with the css maybe it's just your network
