### ISSUE TITLE
Contents of nav bar not perfectly aligned

### ISSUE THREAD

**Issue by Serge-NSN** [transkript/transkript-fe#87]
### Description

The nav icon should be aligned to match the search field adjacent to it (ON MOBILE VIEW).
![Screenshot_20230207_071703](https://user-images.githubusercontent.com/81696072/217164266-d9e848db-d120-4c91-9103-3095ee0816f4.jpg)

**Comment by mofirojean** [comment]
hey @elroykanye,  can i work on this ?
